import {
  Banknote,
  BookOpen,
  Briefcase,
  Building2,
  Calculator,
  Calendar,
  Car,
  ChartColumn,
  ChartPie,
  Clock,
  Cloud,
  CreditCard,
  Database,
  Factory,
  FileSpreadsheet,
  FileText,
  Flag,
  FolderOpen,
  Globe,
  GraduationCap,
  HeartPulse,
  House,
  Landmark,
  LifeBuoy,
  Link2,
  Mail,
  MapPin,
  Megaphone,
  MessageSquare,
  Phone,
  Plane,
  Printer,
  Receipt,
  Scale,
  Server,
  Settings,
  Shield,
  ShoppingCart,
  Star,
  Store,
  TrendingUp,
  Truck,
  Users,
  Wallet,
  Wrench,
  type LucideIcon,
} from "lucide-react";

/**
 * The icons a link card can use. All of them are bundled with the dashboard: nothing is ever
 * fetched for a card. A link stores the key; an unknown key falls back to the default.
 */
export const LINK_ICONS: Record<string, { icon: LucideIcon; label: string }> = {
  link: { icon: Link2, label: "Link" },
  globe: { icon: Globe, label: "Website" },
  landmark: { icon: Landmark, label: "Government or bank" },
  building: { icon: Building2, label: "Company" },
  banknote: { icon: Banknote, label: "Money" },
  card: { icon: CreditCard, label: "Card" },
  wallet: { icon: Wallet, label: "Wallet" },
  receipt: { icon: Receipt, label: "Receipt" },
  calculator: { icon: Calculator, label: "Calculator" },
  document: { icon: FileText, label: "Document" },
  spreadsheet: { icon: FileSpreadsheet, label: "Spreadsheet" },
  folder: { icon: FolderOpen, label: "Folder" },
  calendar: { icon: Calendar, label: "Calendar" },
  clock: { icon: Clock, label: "Time" },
  mail: { icon: Mail, label: "Email" },
  phone: { icon: Phone, label: "Phone" },
  chat: { icon: MessageSquare, label: "Chat" },
  people: { icon: Users, label: "People" },
  briefcase: { icon: Briefcase, label: "Work" },
  scale: { icon: Scale, label: "Legal" },
  shield: { icon: Shield, label: "Insurance or security" },
  book: { icon: BookOpen, label: "Guide" },
  training: { icon: GraduationCap, label: "Training" },
  health: { icon: HeartPulse, label: "Health" },
  travel: { icon: Plane, label: "Travel" },
  car: { icon: Car, label: "Vehicle" },
  truck: { icon: Truck, label: "Delivery" },
  home: { icon: House, label: "Home" },
  factory: { icon: Factory, label: "Factory" },
  store: { icon: Store, label: "Shop" },
  cart: { icon: ShoppingCart, label: "Purchasing" },
  chart: { icon: ChartColumn, label: "Report" },
  pie: { icon: ChartPie, label: "Breakdown" },
  trend: { icon: TrendingUp, label: "Growth" },
  cloud: { icon: Cloud, label: "Cloud" },
  database: { icon: Database, label: "Database" },
  server: { icon: Server, label: "Server" },
  settings: { icon: Settings, label: "Settings" },
  tools: { icon: Wrench, label: "Tools" },
  printer: { icon: Printer, label: "Printing" },
  star: { icon: Star, label: "Favourite" },
  flag: { icon: Flag, label: "Flag" },
  place: { icon: MapPin, label: "Place" },
  news: { icon: Megaphone, label: "Announcements" },
  help: { icon: LifeBuoy, label: "Help" },
};

export const DEFAULT_ICON = "link";

export function linkIcon(key: string | null | undefined): LucideIcon {
  return (LINK_ICONS[key ?? ""] ?? LINK_ICONS[DEFAULT_ICON]!).icon;
}
